// Generated by CoffeeScript 1.10.0
var imageContext;

chrome.runtime.onInstalled.addListener(function(reason, previousVersion) {
  if (reason.reason === 'install') {
    return Messager.send({
      extension_installed: 'first_time'
    });
  }
});

chrome.browserAction.setBadgeText({
  text: ''
});

imageContext = chrome.contextMenus.create({
  title: 'Create anonotation with this image',
  contexts: ['image'],
  onclick: function(info, tab) {
    console.log(info, tab);
    return Messager.send({
      command: 'selected_image',
      data: {
        type: 'image',
        info: info,
        tab: tab
      }
    }, function() {
      var timer;
      chrome.browserAction.setBadgeText({
        text: ''
      });
      timer = new CensorBadge(5 * 1000, 600);
      return timer.start();
    });
  }
});
