// Generated by CoffeeScript 1.10.0
var optionsFields, restore_options, save_options;

optionsFields = ['dbUrl', 'dbUsername', 'dbPassword', 'creatorId', 'creatorName', 'creatorNick'];

save_options = function() {
  var field, i, len, toSetOptions;
  toSetOptions = {};
  for (i = 0, len = optionsFields.length; i < len; i++) {
    field = optionsFields[i];
    toSetOptions[field] = document.getElementById(field).value;
  }
  return chrome.storage.sync.set(toSetOptions, function() {
    var status;
    status = document.getElementById('status');
    status.textContent = 'Options saved.';
    return setTimeout((function() {
      return status.textContent = '';
    }), 1000);
  });
};

restore_options = function() {
  return chrome.storage.sync.get(function(items) {
    var field, i, len;
    for (i = 0, len = optionsFields.length; i < len; i++) {
      field = optionsFields[i];
      if (items[field] != null) {
        document.getElementById(field).value = items[field];
      }
    }
  });
};

document.addEventListener('DOMContentLoaded', restore_options);

document.getElementById('save').addEventListener('click', save_options);
